pluginManagement { 
    repositories { 
        **ARTIFACTORYREPOSITORY**

        // 国内镜像优先
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }

        gradlePluginPortal() 
        google() 
        mavenCentral() 
    } 
} 
 
include ':launcher', ':unityLibrary' 
**INCLUDES** 
 
dependencyResolutionManagement { 
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS) 
    repositories { 
        **ARTIFACTORYREPOSITORY**

        // 国内镜像优先
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }

        google() 
        mavenCentral() 

        flatDir { 
            dirs "${project(':unityLibrary').projectDir}/libs" 
        } 
    } 
}